services:
  api:
    image: 111169964335.dkr.ecr.us-east-1.amazonaws.com/vault-api:latest
    expose:
      - "8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - vault_network

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - vault_network

networks:
  vault_network: